services:
   notulensi-api:
      container_name: notulensi-api
      image: notulensi-api
      build:
         context: ./api
         dockerfile: ./Dockerfile
      ports:
         - 1013:80
      volumes:
         - ./api:/var/www/html
      restart: always

   notulensi-frontend:
      container_name: notulensi-frontend
      image: notulensi-frontend
      build:
         context: ./frontend
         dockerfile: ./Dockerfile
      ports:
         - "1014:80"
      environment:
         - NODE_ENV=production
      restart: always
      depends_on:
         - notulensi-api

   notulensi-backend:
      container_name: notulensi-backend
      image: notulensi-backend
      build:
         context: ./backend
         dockerfile: ./Dockerfile
      volumes:
         - ./backend/dist:/usr/share/nginx/html
      ports:
         - "1015:80"
      environment:
         - NODE_ENV=production
      restart: always
      depends_on:
         - notulensi-api
